apiVersion: apps/v1
kind: Deployment
metadata:
 name: sample-deployment
 labels:
   app: sample
spec:
 replicas: 3
 selector:
   matchLabels:
     app: sample
 template:
   metadata:
     labels:
       app: sample
   spec:
     containers:
     - name: sample-container
       image: nginx:1.25.3
       ports:
       - containerPort: 80
